### ISSUE TITLE
Typing issues

### ISSUE THREAD

**Issue by C0deH4cker** [codyd51/axle#11]
- [ ] After boot, the first few characters I type show up as `7`s. That goes away after typing a few characters.
- [ ] Typing keys in quick succession will drop certain keys, meaning I have to type slowly for it to work properly

**Comment by C0deH4cker** [comment]
I bet it has something to do with https://github.com/codyd51/axle/blob/master/src/kernel/drivers/kb/kb.c#L61, and even if it doesn't, that's a horrible way to append an element to an array. Please store a size along with the buffer, and use that (rather than strlen to recompute the size each time).

**Comment by codyd51** [comment]
Good call, I replaced that with an `array_m` and wrapped the sections where we modify it with a mutex in commit 3e960f6.

**Comment by codyd51** [comment]
With new keyboard driver and 'P'/'H' bug fixed in recent commits, this issue is resolved.
