### ISSUE TITLE
 error: 'read' undeclared (first use in this function)

### ISSUE THREAD

**Issue by 112madgamer** [codyd51/axle#13]
Hey Cody great work on axle I have been compiling axle regularly and recently been hitting this error I have my cross compiler setup right since it has been working since you released it public any ideas why this is happening?

`src/kernel/util/syscall/sysfuncs.c:26:21: error: 'read' undeclared (first use in this function)
  sys_insert((void*)&read);
                     ^~~~
src/kernel/util/syscall/sysfuncs.c:26:21: note: each undeclared identifier is reported only once for each function it appears in
make: *** [.objs/kernel/util/syscall/sysfuncs.o] Error 1`

**Comment by rdrnt** [comment]
Was having this issue also, comment/delete line 26 ```sys_insert((void*)&read);``` in `src/kernel/util/syscall/sysfuncs.c` .

**Comment by codyd51** [comment]
Hi!

I haven't committed a `read` as file descriptors are not fully implemented yet. However, I should have included a stub so that compilation wouldn't fail. You can define a stub function yourself, or simply remove the line that references `read` as @rdrnt suggests.

By the way, I think it's really cool that there's someone out there who's following along with axle development and compiling it regularly. Let me know if you ever have any questions/suggestions/thoughts :-)

I'm going to leave this issue open until I implement file descriptors.

**Comment by 112madgamer** [comment]
Well I commented out that line but I still get errors `i686-elf-gcc -std=gnu99 -ffreestanding -Wall -Wextra -I ./src -o .objs/kernel/util/syscall/sysfuncs.o -c src/kernel/util/syscall/sysfuncs.c
In file included from ./src/std/array_o.h:5:0,
                 from ./src/std/kheap.h:5,
                 from ./src/std/std.h:13,
                 from src/kernel/util/syscall/syscall.h:4,
                 from src/kernel/util/syscall/sysfuncs.h:4,
                 from src/kernel/util/syscall/sysfuncs.c:1:
./src/std/array_m.h:32:1: warning: 'inline' is not at beginning of declaration -Wold-style-declaration]
 __attribute__((always_inline)) type_t inline array_m_lookup(array_m* array, int32_t i) {
 ^~~~~~~~~~~~~
In file included from ./src/kernel/util/multitasking/tasks/task.h:6:0,
                 from src/kernel/util/syscall/sysfuncs.h:5,
                 from src/kernel/util/syscall/sysfuncs.c:1:
./src/std/array_l.h:33:1: warning: 'inline' is not at beginning of declaration -Wold-style-declaration]
 __attribute__((always_inline)) type_t inline array_l_lookup(array_l* array, int32_t idx) {
 ^~~~~~~~~~~~~
In file included from src/kernel/util/syscall/sysfuncs.h:5:0,
                 from src/kernel/util/syscall/sysfuncs.c:1:
./src/kernel/util/multitasking/tasks/task.h:58:19: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
 volatile uint32_t task_switch();
                   ^~~~~~~~~~~
src/kernel/util/syscall/sysfuncs.c: In function 'yield':
src/kernel/util/syscall/sysfuncs.c:14:2: warning: implicit declaration of function 'block_task' [-Wimplicit-function-declaration]
  block_task(current_task, reason);
  ^~~~~~~~~~
i686-elf-gcc -ffreestanding -nostdlib -lgcc -T resources/linker.ld -o isodir/boot/axle.bin .objs/crypto/aes.o .objs/crypto/sha256.o .objs/gfx/font/font.o .objs/gfx/lib/color.o .objs/gfx/lib/gfx.o .objs/gfx/lib/point.o .objs/gfx/lib/rect.o .objs/gfx/lib/shader.o .objs/gfx/lib/shapes.o .objs/gfx/lib/size.o .objs/gfx/lib/view.o .objs/kernel/kernel.o .objs/kernel/drivers/ide/ide.o .objs/kernel/drivers/kb/kb.o .objs/kernel/drivers/mouse/mouse.o .objs/kernel/drivers/pci/pci_detect.o .objs/kernel/drivers/pit/pit.o .objs/kernel/drivers/rtc/clock.o .objs/kernel/drivers/terminal/terminal.o .objs/kernel/drivers/vesa/vesa.o .objs/kernel/drivers/vga/vga.o .objs/kernel/util/elf/elf.o .objs/kernel/util/interrupts/isr.o .objs/kernel/util/kbman/kbman.o .objs/kernel/util/multitasking/util.o .objs/kernel/util/multitasking/tasks/task.o .objs/kernel/util/mutex/mutex.o .objs/kernel/util/paging/descriptor_tables.o .objs/kernel/util/paging/paging.o .objs/kernel/util/syscall/syscall.o .objs/kernel/util/syscall/sysfuncs.o .objs/kernel/util/vfs/fs.o .objs/kernel/util/vfs/initrd.o .objs/lib/iberty/iberty.o .objs/std/array_l.o .objs/std/array_m.o .objs/std/array_o.o .objs/std/common.o .objs/std/ctype.o .objs/std/kheap.o .objs/std/math.o .objs/std/memcpy.o .objs/std/memory.o .objs/std/panic.o .objs/std/printf.o .objs/std/rand.o .objs/std/sincostan.o .objs/std/std.o .objs/std/string.o .objs/std/timer.o .objs/tests/gfx_test.o .objs/tests/test.o .objs/user/shell/shell.o .objs/user/shell/programs/asmjit/asmjit.o .objs/user/shell/programs/rexle/rexle.o .objs/user/shell/programs/snake/snake.o .objs/user/xserv/xserv.o .objs/boot/boot.o .objs/boot/checkA20.o .objs/boot/enableA20.o .objs/kernel/bios/int32.o .objs/kernel/util/interrupts/interrupt.o .objs/kernel/util/multitasking/tasks/process.o .objs/kernel/util/paging/gdt.o .objs/kernel/util/paging/paging_util.o
.objs/kernel/util/multitasking/tasks/task.o: In function `setup_fds':
task.c:(.text+0x25): undefined reference to `stdin_read'
task.c:(.text+0x3c): undefined reference to `stdout_read'
task.c:(.text+0x53): undefined reference to `stderr_read'
collect2: error: ld returned 1 exit status
make: *** [isodir/boot/axle.bin] Error 1`

**Comment by rdrnt** [comment]
In `/src/kernel/util/multitasking/tasks/task.c` comment out the following lines -

```
array_m_insert(task->files, stdin_read);
array_m_insert(task->files, stdout_read);
array_m_insert(task->files, stderr_read);
```

Though I am fairly sure this was fixed in the latest commit.

**Comment by 112madgamer** [comment]
Okay I got it running but hopefully in a few commits it should be working fine
