### ISSUE TITLE
Console is still receiving input in window manager

### ISSUE THREAD

**Issue by filfat** [codyd51/axle#20]
After a little bit of playing around with the window manager i noticed that the console still seems to receive input.

To verify this you can type "startx" and pressing enter while you're inside the window manager to initialize it while you're running it. This leads to a lot of amusing graphical glitches.

(This is tested on the first release)

**Comment by codyd51** [comment]
Hah, seems you're right. Looks like I've accidentally broken the `first_responder` concept. I'll look into this.

Additionally, as a result of the same bug, if using 'WASD' to move around in rexle, when you quit rexle all of the keys you used to move will be printed in shell history

**Comment by codyd51** [comment]
`first_responder` functionality is restored as of commit 9c0415c459d2ad.
