### ISSUE TITLE
Support for compiling on Linux based systems

### ISSUE THREAD

**Issue by rbheromax** [codyd51/axle#27]
Any plans on updating the build system to support compilation on Linux based systems? I can make a few pull-requests for it if necessary (doesn't break any previous code)

**Comment by uroboro** [comment]
This should require changes in the Makefile as I understand. Is there more to it than that?

**Comment by rbheromax** [comment]
A few files will need to be updated. install.sh includes some mac specific stuff (packages will have to be installed manually for linux, xorriso was killer to get for Solus OS), fsgen.c and std_base.h as well as the above mentioned Makefile
Successful build after those small changes, installing proper packages, and running this command:
"make CC=gcc -m32 ISO_MAKER=grub-mkrescue axle.iso"

**Comment by codyd51** [comment]
Support for compiling on linux would be great to have. I'd gladly welcome any pull requests you'd like to contribute!

**Comment by rbheromax** [comment]
I'll get everything I have together and cleaned up for you so the commits are as clean as possible. Is he current code-base updated and stable-ish?

**Comment by rbheromax** [comment]
Submitted pull request :D

**Comment by codyd51** [comment]
Great! I'll check that out now.
